/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package introduction_to_java_programming;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        final var students = new boolean[31];
        try (final var sc = new Scanner(System.in)) {
            for (int i = 0; i < 28; ++i) {
                final var id = sc.nextInt();
                students[id] = true;
            }
        }

        for (int i = 1; i < students.length; ++i)
            if (!students[i])
                System.out.println(i);
    }
}
